INSERT INTO AFTER_SALE_APPLICATION 
  (APPLICATIONID, DESCRIPTION, APPLICATIONTIME, ORDERID, AFTERSALESTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT)
VALUES
  (2, NULL, TO_TIMESTAMP('2025-09-06T02:58:17.767413', 'YYYY-MM-DD"T"HH24:MI:SS.FF'), 1001, N'Pending', NULL, NULL, NULL);

INSERT INTO AFTER_SALE_APPLICATION 
  (APPLICATIONID, DESCRIPTION, APPLICATIONTIME, ORDERID, AFTERSALESTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT)
VALUES
  (3, NULL, TO_TIMESTAMP('2025-09-06T03:00:47.792245', 'YYYY-MM-DD"T"HH24:MI:SS.FF'), 2001, N'Pending', NULL, NULL, NULL);

INSERT INTO AFTER_SALE_APPLICATION 
  (APPLICATIONID, DESCRIPTION, APPLICATIONTIME, ORDERID, AFTERSALESTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT)
VALUES
  (4, NULL, TO_TIMESTAMP('2025-09-06T03:00:47.792990', 'YYYY-MM-DD"T"HH24:MI:SS.FF'), 2002, N'Pending', NULL, NULL, NULL);

INSERT INTO AFTER_SALE_APPLICATION 
  (APPLICATIONID, DESCRIPTION, APPLICATIONTIME, ORDERID, AFTERSALESTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT)
VALUES
  (10, N'送来的宫保鸡丁里好像没有花生', TO_TIMESTAMP('2025-09-06T13:52:10.747040', 'YYYY-MM-DD"T"HH24:MI:SS.FF'), 1001, N'Completed', N'必须放花生', N'偷工减料', N'全额退款');

INSERT INTO AFTER_SALE_APPLICATION 
  (APPLICATIONID, DESCRIPTION, APPLICATIONTIME, ORDERID, AFTERSALESTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT)
VALUES
  (21, N'没看备注', TO_TIMESTAMP('2025-09-11T17:09:12.438987300', 'YYYY-MM-DD"T"HH24:MI:SS.FF'), 131, N'Completed', N'记得下次补偿用户', N'无', N'商家道歉');

INSERT INTO AFTER_SALE_APPLICATION 
  (APPLICATIONID, DESCRIPTION, APPLICATIONTIME, ORDERID, AFTERSALESTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT)
VALUES
  (1, N'汤洒了一点，希望补偿', TO_TIMESTAMP('2025-08-30T19:58:01.658323', 'YYYY-MM-DD"T"HH24:MI:SS.FF'), 1002, N'Completed', N'包装破损', N'用户情况属实，商家负责', N'全额退款');

INSERT INTO AFTER_SALE_APPLICATION 
  (APPLICATIONID, DESCRIPTION, APPLICATIONTIME, ORDERID, AFTERSALESTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT)
VALUES
  (23, N'加了太多香菜', TO_TIMESTAMP('2025-09-11T17:11:29.479707700', 'YYYY-MM-DD"T"HH24:MI:SS.FF'), 131, N'Pending', NULL, NULL, N'-');

INSERT INTO AFTER_SALE_APPLICATION 
  (APPLICATIONID, DESCRIPTION, APPLICATIONTIME, ORDERID, AFTERSALESTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT)
VALUES
  (22, N'没看备注', TO_TIMESTAMP('2025-09-11T17:09:12.439018', 'YYYY-MM-DD"T"HH24:MI:SS.FF'), 131, N'Completed', N'怎么还不看备注', N'无', N'全额退款');
