INSERT INTO COURIERS
(USERID, COURIERREGISTRATIONTIME, VEHICLETYPE, REPUTATIONPOINTS, TOTALDELIVERIES, AVGDELIVERYTIME, AVERAGERATING, MONTHLYSALARY, ISONLINE, COURIERLONGITUDE, COURIERLATITUDE, LASTONLINETIME, COMMISSIONTHISMONTH)
VALUES
(67, TO_TIMESTAMP('2025-09-04 13:36:50', 'YYYY-MM-DD HH24:MI:SS'), 'electric_bike', 0, 0, 0, 0, 0, 'Online', NULL, NULL, NULL, 0);

INSERT INTO COURIERS
(USERID, COURIERREGISTRATIONTIME, VEHICLETYPE, REPUTATIONPOINTS, TOTALDELIVERIES, AVGDELIVERYTIME, AVERAGERATING, MONTHLYSALARY, ISONLINE, COURIERLONGITUDE, COURIERLATITUDE, LASTONLINETIME, COMMISSIONTHISMONTH)
VALUES
(28, TO_TIMESTAMP('2025-09-01 18:01:49', 'YYYY-MM-DD HH24:MI:SS'), 'electric_bike', 0, 0, 0, 0, 0, 'Offline', NULL, NULL, NULL, 0);

INSERT INTO COURIERS
(USERID, COURIERREGISTRATIONTIME, VEHICLETYPE, REPUTATIONPOINTS, TOTALDELIVERIES, AVGDELIVERYTIME, AVERAGERATING, MONTHLYSALARY, ISONLINE, COURIERLONGITUDE, COURIERLATITUDE, LASTONLINETIME, COMMISSIONTHISMONTH)
VALUES
(27, TO_TIMESTAMP('2025-09-01 17:23:57', 'YYYY-MM-DD HH24:MI:SS'), 'electric_bike', 0, 0, 0, 0, 0, 'Offline', NULL, NULL, NULL, 0);

INSERT INTO COURIERS
(USERID, COURIERREGISTRATIONTIME, VEHICLETYPE, REPUTATIONPOINTS, TOTALDELIVERIES, AVGDELIVERYTIME, AVERAGERATING, MONTHLYSALARY, ISONLINE, COURIERLONGITUDE, COURIERLATITUDE, LASTONLINETIME, COMMISSIONTHISMONTH)
VALUES
(148, TO_TIMESTAMP('2025-09-11 17:14:44', 'YYYY-MM-DD HH24:MI:SS'), 'electric_bike', 0, 0, 0, 0, 0, 'Offline', NULL, NULL, NULL, 0);

INSERT INTO COURIERS
(USERID, COURIERREGISTRATIONTIME, VEHICLETYPE, REPUTATIONPOINTS, TOTALDELIVERIES, AVGDELIVERYTIME, AVERAGERATING, MONTHLYSALARY, ISONLINE, COURIERLONGITUDE, COURIERLATITUDE, LASTONLINETIME, COMMISSIONTHISMONTH)
VALUES
(2, TO_TIMESTAMP('2025-08-30 17:24:31', 'YYYY-MM-DD HH24:MI:SS'), '闪电电动车', 120, 0, 0, 4.9, 0, '0', NULL, NULL, NULL, 0);

INSERT INTO COURIERS
(USERID, COURIERREGISTRATIONTIME, VEHICLETYPE, REPUTATIONPOINTS, TOTALDELIVERIES, AVGDELIVERYTIME, AVERAGERATING, MONTHLYSALARY, ISONLINE, COURIERLONGITUDE, COURIERLATITUDE, LASTONLINETIME, COMMISSIONTHISMONTH)
VALUES
(47, TO_TIMESTAMP('2025-09-03 13:32:29', 'YYYY-MM-DD HH24:MI:SS'), '222222', 0, 0, 0, 0, 970, 'Online', 121.213819, 31.289216, NULL, 13.5);

INSERT INTO COURIERS
(USERID, COURIERREGISTRATIONTIME, VEHICLETYPE, REPUTATIONPOINTS, TOTALDELIVERIES, AVGDELIVERYTIME, AVERAGERATING, MONTHLYSALARY, ISONLINE, COURIERLONGITUDE, COURIERLATITUDE, LASTONLINETIME, COMMISSIONTHISMONTH)
VALUES
(69, TO_TIMESTAMP('2025-09-04 16:26:16', 'YYYY-MM-DD HH24:MI:SS'), 'motorcycle', 0, 0, 0, 0, 0, 'Offline', NULL, NULL, NULL, 0);
