INSERT INTO CUSTOMERS
(USERID, DEFAULTADDRESS, REPUTATIONPOINTS, ISMEMBER)
VALUES
(127, '上海市嘉定区曹安公路4800号', 0, 'NotMember');

INSERT INTO CUSTOMERS
(USERID, DEFAULTADDRESS, REPUTATIONPOINTS, ISMEMBER)
VALUES
(30, '吉林市第一中学', 0, 'NotMember');

INSERT INTO CUSTOMERS
(USERID, DEFAULTADDRESS, REPUTATIONPOINTS, ISMEMBER)
VALUES
(1, '北京市海淀区中关村大街1号', 100, 'NotMember');

INSERT INTO CUSTOMERS
(USERID, DEFAULTADDRESS, REPUTATIONPOINTS, ISMEMBER)
VALUES
(5, '上海市浦东新区世纪大道100号', 100, 'Member');

INSERT INTO CUSTOMERS
(USERID, DEFAULTADDRESS, REPUTATIONPOINTS, ISMEMBER)
VALUES
(11, NULL, 0, 'NotMember');

INSERT INTO CUSTOMERS
(USERID, DEFAULTADDRESS, REPUTATIONPOINTS, ISMEMBER)
VALUES
(89, NULL, 0, 'NotMember');

INSERT INTO CUSTOMERS
(USERID, DEFAULTADDRESS, REPUTATIONPOINTS, ISMEMBER)
VALUES
(68, NULL, 0, 'NotMember');
