INSERT INTO DELIVERY_COMPLAINTS
(COMPLAINTID, COMPLAINTREASON, COMPLAINTTIME, COURIERID, CUSTOMERID, DELIVERYTASKID, COMPLAINTSTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT, FINEAMOUNT)
VALUES
(10, '骑手提前点击了送达', TO_TIMESTAMP('2025-09-06 13:52:10.842214', 'YYYY-MM-DD HH24:MI:SS.FF6'), 47, 5, 102, 'Completed', '欺骗消费者', '按迟到处理，外加罚款', '警告处分', 10);

INSERT INTO DELIVERY_COMPLAINTS
(COMPLAINTID, COMPLAINTREASON, COMPLAINTTIME, COURIERID, CUSTOMERID, DELIVERYTASKID, COMPLAINTSTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT, FINEAMOUNT)
VALUES
(21, '骑手偷吃我外卖！', TO_TIMESTAMP('2025-09-11 16:50:54.674322', 'YYYY-MM-DD HH24:MI:SS.FF6'), 47, 30, 3, 'Pending', NULL, NULL, '-', NULL);

INSERT INTO DELIVERY_COMPLAINTS
(COMPLAINTID, COMPLAINTREASON, COMPLAINTTIME, COURIERID, CUSTOMERID, DELIVERYTASKID, COMPLAINTSTATE, PROCESSINGREASON, PROCESSINGREMARK, PROCESSINGRESULT, FINEAMOUNT)
VALUES
(1, '骑手态度不好', TO_TIMESTAMP('2025-08-30 19:58:01.754893', 'YYYY-MM-DD HH24:MI:SS.FF6'), 2, 1, 1, 'Completed', '骑手对顾客态度恶劣', '骑手平时工作态度良好，只进行警告', '警告处分', NULL);
