INSERT INTO EVALUATE_AFTER_SALE (ADMINID, APPLICATIONID) VALUES (31, 1);
INSERT INTO EVALUATE_AFTER_SALE (ADMINID, APPLICATIONID) VALUES (31, 10);
INSERT INTO EVALUATE_AFTER_SALE (ADMINID, APPLICATIONID) VALUES (31, 21);
INSERT INTO EVALUATE_AFTER_SALE (ADMINID, APPLICATIONID) VALUES (31, 22);
INSERT INTO EVALUATE_AFTER_SALE (ADMINID, APPLICATIONID) VALUES (31, 23);
