INSERT INTO EVALUATE_COMPLAINT (ADMINID, COMPLAINTID) VALUES (31, 1);
INSERT INTO EVALUATE_COMPLAINT (ADMINID, COMPLAINTID) VALUES (31, 10);
INSERT INTO EVALUATE_COMPLAINT (ADMINID, COMPLAINTID) VALUES (31, 21);
