-- =============================================
-- 插入优惠券测试数据 (Oracle 19c)
-- =============================================

-- 首先检查当前数据
SELECT COUNT(*) AS "当前优惠券数量" FROM COUPON_MANAGERS;

-- 检查当前最大的COUPONMANAGERID
SELECT NVL(MAX(COUPONMANAGERID), 0) AS "当前最大ID" FROM COUPON_MANAGERS;

-- 插入测试优惠券数据
-- 注意：SELLERID = 3 对应默认商家ID，STOREID = 101 对应默认店铺ID
-- 使用序列或手动指定ID避免主键冲突

-- 1. 满减券测试数据
INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '新用户专享券', 0, 50.00, 10.00, NULL,
    1000, 25, TIMESTAMP '2024-01-01 00:00:00', TIMESTAMP '2024-12-31 23:59:59',
    '新用户专享优惠券，满50减10元', 101, 3
);

INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '会员满减券', 0, 200.00, 25.00, NULL,
    500, 12, TIMESTAMP '2024-01-01 00:00:00', TIMESTAMP '2024-12-31 23:59:59',
    '会员专享，满200减25元', 101, 3
);

INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '周末特惠券', 0, 100.00, 15.00, NULL,
    800, 8, TIMESTAMP '2024-01-01 00:00:00', TIMESTAMP '2024-12-31 23:59:59',
    '周末特惠，满100减15元', 101, 3
);

-- 2. 折扣券测试数据
INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '会员折扣券', 1, 0.00, 0.00, 0.80,
    300, 18, TIMESTAMP '2024-01-01 00:00:00', TIMESTAMP '2024-12-31 23:59:59',
    '会员专享8折优惠券', 101, 3
);

INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '学生折扣券', 1, 0.00, 0.00, 0.85,
    200, 5, TIMESTAMP '2024-01-01 00:00:00', TIMESTAMP '2024-12-31 23:59:59',
    '学生专享8.5折优惠券', 101, 3
);

INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '生日特惠券', 1, 0.00, 0.00, 0.70,
    100, 3, TIMESTAMP '2024-01-01 00:00:00', TIMESTAMP '2024-12-31 23:59:59',
    '生日专享7折优惠券', 101, 3
);

-- 3. 不同状态的优惠券测试数据

-- 已过期的优惠券
INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '过期测试券', 0, 30.00, 5.00, NULL,
    100, 15, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-12-31 23:59:59',
    '已过期的测试优惠券', 101, 3
);

-- 未开始的优惠券
INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '未来优惠券', 0, 80.00, 12.00, NULL,
    200, 0, TIMESTAMP '2025-01-01 00:00:00', TIMESTAMP '2025-12-31 23:59:59',
    '未来生效的优惠券', 101, 3
);

-- 4. 其他商家的优惠券（用于测试权限控制）
INSERT INTO COUPON_MANAGERS (
    COUPONMANAGERID, COUPONNAME, COUPONTYPE, MINIMUMSPEND, DISCOUNTAMOUNT, DISCOUNTRATE, 
    TOTALQUANTITY, USEDQUANTITY, VALIDFROM, VALIDTO, DESCRIPTION, 
    STOREID, SELLERID
) VALUES (
    (SELECT NVL(MAX(COUPONMANAGERID), 0) + 1 FROM COUPON_MANAGERS), 
    '其他商家券', 0, 60.00, 8.00, NULL,
    150, 7, TIMESTAMP '2024-01-01 00:00:00', TIMESTAMP '2024-12-31 23:59:59',
    '其他商家的优惠券，用于测试权限', 102, 4
);

-- 提交事务
COMMIT;

-- 验证插入结果
SELECT 
    COUPONMANAGERID AS "优惠券ID",
    COUPONNAME AS "优惠券名称",
    CASE COUPONTYPE 
        WHEN 0 THEN '满减券' 
        WHEN 1 THEN '折扣券' 
    END AS "类型",
    CASE COUPONTYPE 
        WHEN 0 THEN '满¥' || MINIMUMSPEND || '减¥' || DISCOUNTAMOUNT
        WHEN 1 THEN (DISCOUNTRATE * 10) || '折'
    END AS "优惠内容",
    TOTALQUANTITY AS "总数量",
    USEDQUANTITY AS "已使用",
    VALIDFROM AS "开始时间",
    VALIDTO AS "结束时间",
    CASE 
        WHEN VALIDTO < CURRENT_TIMESTAMP THEN '已过期'
        WHEN VALIDFROM > CURRENT_TIMESTAMP THEN '未开始'
        ELSE '有效'
    END AS "状态",
    SELLERID AS "商家ID"
FROM COUPON_MANAGERS 
WHERE SELLERID = 3
ORDER BY COUPONMANAGERID;

-- 统计信息
SELECT 
    '商家ID=3的优惠券统计' AS "统计项目",
    COUNT(*) AS "总数量",
    COUNT(CASE WHEN VALIDTO >= CURRENT_TIMESTAMP AND VALIDFROM <= CURRENT_TIMESTAMP THEN 1 END) AS "有效数量",
    COUNT(CASE WHEN VALIDTO < CURRENT_TIMESTAMP THEN 1 END) AS "已过期数量",
    COUNT(CASE WHEN VALIDFROM > CURRENT_TIMESTAMP THEN 1 END) AS "未开始数量",
    SUM(USEDQUANTITY) AS "总使用次数"
FROM COUPON_MANAGERS 
WHERE SELLERID = 3;
