-- =============================================
-- 检查COUPON_MANAGERS和COUPONS表的外键约束关系
-- =============================================

-- 1. 检查COUPON_MANAGERS表的所有外键约束
SELECT 
    uc.CONSTRAINT_NAME AS "约束名称",
    uc.CONSTRAINT_TYPE AS "约束类型",
    uc.TABLE_NAME AS "表名",
    ucc.COLUMN_NAME AS "外键列名",
    uc.R_CONSTRAINT_NAME AS "引用约束名",
    uc.R_TABLE_NAME AS "引用表名"
FROM USER_CONSTRAINTS uc
JOIN USER_CONS_COLUMNS ucc ON uc.CONSTRAINT_NAME = ucc.CONSTRAINT_NAME
WHERE uc.TABLE_NAME = 'COUPON_MANAGERS' 
    AND uc.CONSTRAINT_TYPE = 'R'
ORDER BY ucc.POSITION;

-- 2. 检查COUPONS表的所有外键约束
SELECT 
    uc.CONSTRAINT_NAME AS "约束名称",
    uc.CONSTRAINT_TYPE AS "约束类型",
    uc.TABLE_NAME AS "表名",
    ucc.COLUMN_NAME AS "外键列名",
    uc.R_CONSTRAINT_NAME AS "引用约束名",
    uc.R_TABLE_NAME AS "引用表名"
FROM USER_CONSTRAINTS uc
JOIN USER_CONS_COLUMNS ucc ON uc.CONSTRAINT_NAME = ucc.CONSTRAINT_NAME
WHERE uc.TABLE_NAME = 'COUPONS' 
    AND uc.CONSTRAINT_TYPE = 'R'
ORDER BY ucc.POSITION;

-- 3. 检查COUPON_MANAGERS表引用的表是否存在
SELECT 
    'STORES表' AS "引用表",
    COUNT(*) AS "记录数"
FROM STORES;

SELECT 
    'SELLERS表' AS "引用表",
    COUNT(*) AS "记录数"
FROM SELLERS;

-- 4. 检查COUPONS表引用的表是否存在
SELECT 
    'CUSTOMERS表' AS "引用表",
    COUNT(*) AS "记录数"
FROM CUSTOMERS;

SELECT 
    'FOOD_ORDERS表' AS "引用表",
    COUNT(*) AS "记录数"
FROM FOOD_ORDERS;

-- 5. 检查具体的引用关系
SELECT 
    'COUPON_MANAGERS -> STORES' AS "关系",
    COUNT(*) AS "COUPON_MANAGERS记录数"
FROM COUPON_MANAGERS cm
LEFT JOIN STORES s ON cm.STOREID = s.STOREID
WHERE s.STOREID IS NULL;

SELECT 
    'COUPON_MANAGERS -> SELLERS' AS "关系",
    COUNT(*) AS "COUPON_MANAGERS记录数"
FROM COUPON_MANAGERS cm
LEFT JOIN SELLERS se ON cm.SELLERID = se.USERID
WHERE se.USERID IS NULL;

-- 6. 检查STOREID=101和SELLERID=3是否存在
SELECT 
    'STOREID=101' AS "检查项",
    CASE WHEN EXISTS(SELECT 1 FROM STORES WHERE STOREID = 101) 
         THEN '存在' 
         ELSE '不存在' 
    END AS "状态";

SELECT 
    'SELLERID=3' AS "检查项",
    CASE WHEN EXISTS(SELECT 1 FROM SELLERS WHERE USERID = 3) 
         THEN '存在' 
         ELSE '不存在' 
    END AS "状态";
