-- 检查SELLERS表的实际结构
-- 这个脚本用来确认SELLERS表中实际存在的列

-- 1. 查看SELLERS表的完整结构
SELECT '=== SELLERS表结构 ===' as INFO;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    DATA_PRECISION,
    DATA_SCALE,
    NULLABLE,
    DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SELLERS'
ORDER BY COLUMN_ID;

-- 2. 查看SELLERS表的所有数据
SELECT '=== SELLERS表数据 ===' as INFO;
SELECT 
    USERID,
    SELLERREGISTRATIONTIME,
    REPUTATIONPOINTS,
    BANSTATUS
FROM SELLERS 
ORDER BY USERID;

-- 3. 检查是否有USERID=3的商家
SELECT '=== 检查USERID=3的商家 ===' as INFO;
SELECT 
    USERID,
    SELLERREGISTRATIONTIME,
    REPUTATIONPOINTS,
    BANSTATUS
FROM SELLERS 
WHERE USERID = 3;

-- 4. 查看USERS表结构
SELECT '=== USERS表结构 ===' as INFO;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    DATA_PRECISION,
    DATA_SCALE,
    NULLABLE,
    DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USERS'
ORDER BY COLUMN_ID;

-- 5. 检查是否有USERID=3的用户
SELECT '=== 检查USERID=3的用户 ===' as INFO;
SELECT 
    USERID,
    USERNAME,
    EMAIL,
    USERSTATUS
FROM USERS 
WHERE USERID = 3;

-- 6. 关联查询：SELLERS和USERS
SELECT '=== SELLERS和USERS关联查询 ===' as INFO;
SELECT 
    s.USERID,
    s.SELLERREGISTRATIONTIME,
    s.REPUTATIONPOINTS,
    s.BANSTATUS,
    u.USERNAME,
    u.EMAIL,
    u.USERSTATUS
FROM SELLERS s
LEFT JOIN USERS u ON s.USERID = u.USERID
WHERE s.USERID = 3;
