-- 检查STORES表的SELLERID字段
-- 这个脚本用来确认STORES表中SELLERID的值

-- 1. 查看STORES表的完整结构（包括SELLERID）
SELECT '=== STORES表完整结构 ===' as INFO;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    DATA_PRECISION,
    DATA_SCALE,
    NULLABLE,
    DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'STORES'
ORDER BY COLUMN_ID;

-- 2. 查看STORES表的所有数据（包括SELLERID）
SELECT '=== STORES表所有数据（包括SELLERID） ===' as INFO;
SELECT 
    STOREID,
    STORENAME,
    STOREADDRESS,
    OPENTIME,
    CLOSETIME,
    AVERAGERATING,
    MONTHLYSALES,
    STOREFEATURES,
    STORECREATIONTIME,
    STORESTATE,
    STORECATEGORY,
    STOREIMAGE,
    SELLERID  -- 关键字段！
FROM STORES 
ORDER BY STOREID;

-- 3. 检查SELLERID=101的记录
SELECT '=== 检查SELLERID=101的记录 ===' as INFO;
SELECT 
    STOREID,
    STORENAME,
    STOREADDRESS,
    SELLERID
FROM STORES 
WHERE SELLERID = 101;

-- 4. 检查STOREID=101的记录
SELECT '=== 检查STOREID=101的记录 ===' as INFO;
SELECT 
    STOREID,
    STORENAME,
    STOREADDRESS,
    SELLERID
FROM STORES 
WHERE STOREID = 101;

-- 5. 查看SELLERS表
SELECT '=== SELLERS表数据 ===' as INFO;
SELECT 
    USERID,
    BANSTATUS,
    REPUTATIONPOINTS
FROM SELLERS 
ORDER BY USERID;

-- 6. 检查是否有USERID=101的商家
SELECT '=== 检查USERID=101的商家 ===' as INFO;
SELECT 
    USERID,
    BANSTATUS,
    REPUTATIONPOINTS
FROM SELLERS 
WHERE USERID = 101;

-- 7. 关联查询：STORES和SELLERS
SELECT '=== STORES和SELLERS关联查询 ===' as INFO;
SELECT 
    s.STOREID,
    s.STORENAME,
    s.SELLERID as STORE_SELLERID,
    sel.USERID as SELLER_USERID,
    sel.BANSTATUS,
    sel.REPUTATIONPOINTS
FROM STORES s
LEFT JOIN SELLERS sel ON s.SELLERID = sel.USERID
ORDER BY s.STOREID;
