-- 重建 STORES 表，确保与数据库设计文档完全匹配
-- 执行前请备份数据！

-- 1. 备份现有数据（如果有的话）
CREATE TABLE STORES_BACKUP AS SELECT * FROM STORES;

-- 2. 删除现有表
DROP TABLE STORES CASCADE CONSTRAINTS;

-- 3. 创建新表，完全按照设计文档
CREATE TABLE STORES (
    STOREID NUMBER(10,0) PRIMARY KEY,
    STORENAME VARCHAR2(50) NOT NULL,
    STOREADDRESS VARCHAR2(100) NOT NULL,
    BUSINESSHOURS DATE NOT NULL,
    AVERAGERATING NUMBER(10,2) DEFAULT 0.00,
    MONTHLYSALES NUMBER(10,0) NOT NULL,
    STOREFEATURES VARCHAR2(500) NOT NULL,
    STORECREATIONTIME DATE NOT NULL,
    SELLERID NUMBER(10,0) NOT NULL
);

-- 4. 添加约束
-- 月销量不小于0的约束
ALTER TABLE STORES ADD CONSTRAINT CK_STORES_MONTHLYSALES CHECK (MONTHLYSALES >= 0);

-- 外键约束
ALTER TABLE STORES ADD CONSTRAINT FK_STORES_SELLERID 
    FOREIGN KEY (SELLERID) REFERENCES SELLERS(USERID);

-- 5. 创建序列（用于自增主键）
CREATE SEQUENCE STORES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 6. 创建触发器（用于自动生成主键）
CREATE OR REPLACE TRIGGER STORES_TRG
    BEFORE INSERT ON STORES
    FOR EACH ROW
BEGIN
    IF :NEW.STOREID IS NULL THEN
        :NEW.STOREID := STORES_SEQ.NEXTVAL;
    END IF;
END;
/

-- 7. 恢复数据（如果有备份数据）
-- 注意：需要根据实际的数据格式调整插入语句
INSERT INTO STORES (
    STOREID,
    STORENAME,
    STOREADDRESS,
    BUSINESSHOURS,
    AVERAGERATING,
    MONTHLYSALES,
    STOREFEATURES,
    STORECREATIONTIME,
    SELLERID
)
SELECT 
    STOREID,
    STORENAME,
    STOREADDRESS,
    -- 转换 BUSINESSHOURS 为 DATE 类型
    CASE 
        WHEN BUSINESSHOURS IS NOT NULL THEN 
            TO_DATE(BUSINESSHOURS, 'YYYY-MM-DD HH24:MI:SS')
        ELSE 
            SYSDATE
    END as BUSINESSHOURS,
    AVERAGERATING,
    MONTHLYSALES,
    STOREFEATURES,
    -- 转换 STORECREATIONTIME 为 DATE 类型
    CASE 
        WHEN STORECREATIONTIME IS NOT NULL THEN 
            TO_DATE(STORECREATIONTIME, 'YYYY-MM-DD HH24:MI:SS')
        ELSE 
            SYSDATE
    END as STORECREATIONTIME,
    SELLERID
FROM STORES_BACKUP;

-- 8. 验证表结构
SELECT '=== 验证表结构 ===' as INFO;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    DATA_PRECISION,
    DATA_SCALE,
    NULLABLE,
    DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'STORES'
ORDER BY COLUMN_ID;

-- 9. 验证约束
SELECT '=== 验证约束 ===' as INFO;
SELECT 
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    SEARCH_CONDITION
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'STORES'
ORDER BY CONSTRAINT_TYPE, CONSTRAINT_NAME;

-- 10. 验证数据
SELECT '=== 验证数据 ===' as INFO;
SELECT 
    STOREID,
    STORENAME,
    STOREADDRESS,
    BUSINESSHOURS,
    AVERAGERATING,
    MONTHLYSALES,
    STOREFEATURES,
    STORECREATIONTIME,
    SELLERID
FROM STORES 
WHERE ROWNUM <= 5;

-- 11. 清理备份表（可选）
-- DROP TABLE STORES_BACKUP; 